name: CI
on:
  push:
    branches: ["main"]

concurrency:
  group: staging
  cancel-in-progress: true

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Setup Tools
        uses: ./.github/actions/tools

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
  
  build:
    name: Build and Test
    needs: dependencies

    runs-on: ubuntu-latest

    steps:
      - name: Setup Tools
        uses: ./.github/workflows/tools.yml

      - name: Build and Test
        run: pnpm turbo build test

  staging-deploy:
    name: Deploy to Staging
    needs: build

    runs-on: ubuntu-latest
    environment: staging
    concurrency: staging

    steps:
      - name: deploy
        run: echo "Deploy to Staging Placeholder"

  
      

