name: CI
on:
  push:
    branches: ["main"]

concurrency:
  group: staging
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tools
        uses: ./.github/actions/dependencies

      - name: Build and Test
        run: pnpm turbo build test

  staging-deploy:
    name: Deploy to Staging
    needs: build

    runs-on: ubuntu-latest
    environment: staging
    concurrency: staging

    steps:
      - name: deploy
        run: echo "Deploy to Staging Placeholder"

  
      

